### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by MonikaPatelIT** [AddSearch/search-ui-react-example#1]
Thank you for your repo work. when I tired to implement same logic on my project I got an error.

```
     "addsearch-js-client": "^0.4.3",
     "addsearch-search-ui": "^0.4.7", 
     "react": "^16.8.6",
      "react-dom": "^16.8.6",
```
![image](https://user-images.githubusercontent.com/9668906/81110276-6eb94980-8f6f-11ea-9942-d8d887937ac7.png)
![image](https://user-images.githubusercontent.com/9668906/81110358-8db7db80-8f6f-11ea-83a5-d3685604c67e.png)

**Comment by anttiai** [comment]
HI! Are you using Next.js in your project? If that's the case, the *window* object is not available due to server-side rendering.

To circumvent this issue, use [dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import) for the component that imports *addsearch-js-client* and *addsearch-search-ui* libraries. 

For example, if you want to use the [App.js](https://github.com/AddSearch/search-ui-react-example/blob/master/src/App.js) from this repository, import it dynamically:

```js
const App = dynamic(
  () => import('./App'),
  {ssr: false}
)
```

After that, the component can be used like any other React component:

```html
<div>
 <App />
</div>
```

Let me know if this helps!
